language: minimal
sudo: required
services:
  - docker
env:
  global:
    secure: bfiSGgj9rJ2lARMUL3r0WED34u8TvenmWS0kLVLskTcOlQdK+i5HFf4vxMyqOtwnBoQCsTFxfJoaCG7sQZm4flbkkXJMUmrAMZtfa6VF0zu+Veio4qmKoVAFOPgXllwkuQ3pMGuhWwIDQ3FstiOIGfvBqKq8Uju0mQjQf0zp24oPTONTmWYhGL7gOTXU7q3GVvPKX612pZOYnM2IDLfrpka9dIWNAA/wfW6Nac8WAiwyprQVwmUBhBC9JvaO4rIpTRpPRK3bbrSRUffk6IAcIzMeYFDIyWtwru/To9fXFvMRNQ3DfQ+fZcFZs/Sy3wOxuQHOxNLlCX5qHzHxKXTDvXScl48kAwsSXIhg1mugCt8U/MMyT1X9xH95OMLFl4J4Ug5md0ZJjzVRI7EhJsbzBrL8nCGA4mHPG4aoRRgLSHTt5e33toLL36SUT7z2VeeY1Gkc47lBMU+A7h6F6Mno1p26OxNBuKutE9hF0DlNmD68Vray8gj2NNyWV7+HxpZd/2iMeNWoNuWCxZ38OPXD5oXTIloeHzTUPqHwm67pxjqO8FeVYlEfH+lf/s+hU0jbCkCNcEo4daQMyZBU7cA/IyZxdDwE2yT3/aqbCik2ct8ErN0uqvIRkWzR7ClomLEczrUUnc+eDO+CRNm4pIoVYcGe5ZA7om+M+Fc3wZmQwJY=
script: make
deploy:
  provider: script
  script: make publish
  on:
    branch: master
    tags: true